"use client";

import Link from "next/link";
import { motion } from "framer-motion";
import { useLang } from "../../lang-provider";

const fadeUp = {
  hidden: { opacity: 0, y: 30 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.6, ease: "easeOut" as const } },
};

const stagger = {
  visible: { transition: { staggerChildren: 0.12 } },
};

const content = {
  back: { fr: "← Retour", en: "← Back" },
  pill: { fr: "Pricing · Modèle économique · Nomad's 2019", en: "Pricing · Business model · Nomad's 2019" },
  subtitle: {
    fr: "Refonte complète du modèle de pricing B2C en 2019. Toujours en vigueur 7 ans plus tard.",
    en: "Complete overhaul of the B2C pricing model in 2019. Still in use 7 years later.",
  },
  situation: { fr: "Situation", en: "Situation" },
  situationP: {
    fr: "Avant 2019, le modèle B2C en bars reposait sur un système de commission plafonnée variable selon le lieu (par exemple 20% jusqu'à 60€ par tournée, zéro au-delà). Deux problèmes : côté ops, je passais une journée entière par mois à recalculer les commissions et émettre une facture par praticien·ne, avec des erreurs récurrentes ; côté praticien·ne·s, le tarif était imprévisible et opaque.",
    en: "Before 2019, the B2C bar model relied on a variable capped commission system by venue (e.g. 20% up to 60€ per round, zero beyond). Two problems: ops-side, I spent a full day each month recalculating commissions and issuing one invoice per practitioner, with recurring errors; practitioner-side, the pricing was unpredictable and opaque.",
  },
  task: { fr: "Task", en: "Task" },
  taskP: {
    fr: "Concevoir un nouveau modèle économique qui résolve la friction opérationnelle interne et améliore la transparence côté praticien·ne·s, sans dégrader le revenu.",
    en: "Design a new business model that solves internal operational friction and improves transparency for practitioners, without degrading revenue.",
  },
  action: { fr: "Action", en: "Action" },
  actionP: {
    fr: "En 2019, j'ai conçu un système de crédits prépayés appelés Mads. Le principe : la praticien·ne achète un pack à l'avance (par exemple 50 Mads à 129,90€), et chaque inscription à une tournée débite un nombre de Mads variable selon le coût d'opération de la ville. J'ai défini la grille tarifaire par ville, fait coder la mécanique dans la plateforme, et accompagné la transition auprès de la communauté. C'est aussi à ce moment-là que j'ai démarré mon parcours no-code : pour automatiser les paiements PayPal et la facturation autour des Mads, j'ai appris à connecter mes outils, et de fil en aiguille j'ai automatisé une grande partie de mes process internes.",
    en: "In 2019, I designed a prepaid credit system called Mads. The principle: practitioners buy a pack upfront (e.g. 50 Mads for 129.90€), and each round registration debits a variable number of Mads based on the city's operating cost. I defined the pricing grid by city, had the mechanics coded into the platform, and managed the community transition. This is also when I started my no-code journey: to automate PayPal payments and billing around Mads, I learned to connect my tools, and gradually automated most of my internal processes.",
  },
  result: { fr: "Résultat", en: "Result" },
  stats: {
    fr: [
      { value: "100%", desc: "de la facturation automatisée : 1 journée de calcul manuel libérée chaque mois, zéro erreur" },
      { value: "60 940€ HT", desc: "de CA en 2024 généré par cette mécanique" },
      { value: "7 ans", desc: "de stabilité sans modification structurelle" },
      { value: "30%", desc: "des praticien·ne·s les plus actif·ve·s consomment 50 à 70% des Mads, indicateur d'engagement net" },
    ],
    en: [
      { value: "100%", desc: "of billing automated: 1 full day of manual calculation freed each month, zero errors" },
      { value: "60,940€", desc: "revenue in 2024 generated by this mechanism" },
      { value: "7 years", desc: "of stability without structural changes" },
      { value: "30%", desc: "of most active practitioners consume 50-70% of Mads, a clear engagement indicator" },
    ],
  },
  statsNote: {
    fr: "Encaissement à l'avance : cash dans la boîte avant que la prestation soit consommée, impact direct sur la trésorerie.",
    en: "Upfront payment: cash in the bank before the service is consumed, direct impact on cash flow.",
  },
  learning: { fr: "Learning", en: "Learning" },
  learningP: {
    fr: "Le déclencheur de mon parcours no-code. Côté produit, j'ai appris qu'un changement de modèle économique réussit quand il résout à la fois une friction ops invisible et une friction utilisateur visible. Et qu'un bon système se mesure à sa stabilité dans le temps : 7 ans sans refonte, c'est mon meilleur indicateur de robustesse.",
    en: "The trigger for my no-code journey. Product-wise, I learned that a business model change succeeds when it solves both an invisible ops friction and a visible user friction. And that a good system is measured by its stability over time: 7 years without redesign is my best robustness indicator.",
  },
} as const;

export default function CaseMadsPage() {
  const { lang } = useLang();
  return (
    <main className="min-h-screen bg-cream text-dark">
      <nav className="fixed top-0 left-0 right-0 z-50 flex items-center justify-between px-6 md:px-12 h-16 bg-cream/90 backdrop-blur-md border-b border-dark/5">
        <Link href="/" className="font-heading text-lg font-bold tracking-tight">
          Alexandra Philibert<span className="text-orange">.</span>
        </Link>
        <a href="/#cases" className="text-sm font-semibold text-dark/40 hover:text-violet transition-colors">{content.back[lang]}</a>
      </nav>

      <motion.div className="max-w-4xl mx-auto px-6 pt-28 pb-24" initial="hidden" animate="visible" variants={stagger}>
        <motion.div variants={fadeUp} className="inline-block bg-violet/10 text-violet text-xs font-bold px-3 py-1.5 rounded-full mb-6">{content.pill[lang]}</motion.div>
        <motion.h1 variants={fadeUp} className="font-heading text-4xl md:text-6xl font-bold tracking-tight mb-6">
          {lang === "fr" ? "Système Mads" : "Mads System"}<span className="text-violet">.</span>
        </motion.h1>
        <motion.p variants={fadeUp} className="text-xl text-dark/50 leading-relaxed mb-16 max-w-2xl">{content.subtitle[lang]}</motion.p>

        <motion.div variants={fadeUp} className="space-y-16">
          <div>
            <h2 className="font-heading text-2xl font-bold mb-6">{content.situation[lang]}</h2>
            <p className="text-dark/65 leading-[1.8]">{content.situationP[lang]}</p>
          </div>
          <div>
            <h2 className="font-heading text-2xl font-bold mb-6">{content.task[lang]}</h2>
            <p className="text-dark/65 leading-[1.8]">{content.taskP[lang]}</p>
          </div>
          <div>
            <h2 className="font-heading text-2xl font-bold mb-6">{content.action[lang]}</h2>
            <p className="text-dark/65 leading-[1.8]">{content.actionP[lang]}</p>
          </div>

          <div className="bg-violet/5 border-l-4 border-violet p-8">
            <h2 className="font-heading text-2xl font-bold mb-6">{content.result[lang]}</h2>
            <div className="grid sm:grid-cols-2 gap-6">
              {content.stats[lang].map((s) => (
                <div key={s.value}>
                  <div className="font-heading text-2xl font-bold text-violet">{s.value}</div>
                  <p className="text-dark/50 text-sm mt-1">{s.desc}</p>
                </div>
              ))}
            </div>
            <p className="text-dark/50 text-sm mt-6">{content.statsNote[lang]}</p>
          </div>

          <div>
            <h2 className="font-heading text-2xl font-bold mb-6">{content.learning[lang]}</h2>
            <p className="text-dark/65 leading-[1.8]">{content.learningP[lang]}</p>
          </div>
        </motion.div>

        <motion.div variants={fadeUp} className="mt-20 pt-10 border-t-2 border-dark/10 flex justify-between">
          <span />
          <Link href="/cases/marseille-fermeture" className="font-mono text-xs uppercase tracking-wider text-dark/40 hover:text-rose transition-colors">
            {lang === "fr" ? "Fermeture Marseille / Aix →" : "Marseille / Aix Closure →"}
          </Link>
        </motion.div>
      </motion.div>
    </main>
  );
}
